mock user changed to USER_ID
gradiviro/jv-internet-shop pull request #8
Opened 2020-09-15 11:20 UTC by gradiviro

2020-09-15 11:22 UTC, floriangeyer21 approved these changes

2020-09-16 05:06 UTC, KseniiaMakarova requested changes

2020-09-16 05:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/DeleteItemFormCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
```suggestion
                .getByUserId((Long) req.getSession().getAttribute(LoginController.USER_ID));
```

2020-09-16 05:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/GetShoppingCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
same
I would also recommend to make a local variable instead of such a long line

2020-09-16 05:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/AddProductToShoppingCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
same

2020-09-16 06:59 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/cart/DeleteItemFormCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
done

2020-09-16 07:03 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/cart/GetShoppingCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
done
I firstly did it with a local variable, but then decided to get rid of them completely, can I leave it like that?)

2020-09-16 07:03 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/product/AddProductToShoppingCartController.java
> +                .getByUserId((Long )req.getSession().getAttribute(LoginController.USER_ID));
done

2020-09-16 07:06 UTC, KseniiaMakarova approved these changes

2020-09-16 07:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/AddProductToShoppingCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
```suggestion
                .getByUserId((Long) req.getSession().getAttribute(LoginController.USER_ID));
```

2020-09-16 07:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/GetShoppingCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
```suggestion
                .getByUserId((Long) req.getSession().getAttribute(LoginController.USER_ID));
```

2020-09-16 07:06 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/DeleteItemFormCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
```suggestion
                .getByUserId((Long) req.getSession().getAttribute(LoginController.USER_ID));
```

2020-09-16 07:16 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/product/AddProductToShoppingCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
done

2020-09-16 07:16 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/cart/DeleteItemFormCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
done

2020-09-16 07:16 UTC, gradiviro commented on src/main/java/com/internet/shop/controllers/cart/GetShoppingCartController.java
> +                .getByUserId((Long)req.getSession().getAttribute(LoginController.USER_ID));
done

2020-09-16 07:30 UTC, merged